kselftest: merge fixes to Android.bp and patches
Added new tests in 5.17:
futex_requeue
futex_wait
futex_waitv
vdso_test_abi
vdso_test_clock_getres
vdso_test_getcpu
vdso_test_gettimeofday

Disabled:
vdso_test_correctness

Removed:
vdso_test

Bug: 189333904
Signed-off-by: Edward Liaw <edliaw@google.com>
Change-Id: I18a124c1ef878ab374b849f479a35e4ac85ad1ca

diff --git a/android/patches/0012-run-vmtests.patch b/android/patches/0012-run-vmtests.patch
--- a/android/patches/0012-run-vmtests.patch
+++ b/android/patches/0012-run-vmtests.patch
@@ -1,11 +1,23 @@
+From 9d2c36f2fc8ece386e2428ba7c66e3a2fa6bef78 Mon Sep 17 00:00:00 2001
+From: Edward Liaw <edliaw@google.com>
+Date: Tue, 19 Apr 2022 23:09:36 +0000
+Subject: [PATCH 12/24] run vmtests
+
 The hugepage-mmap, hugepage-shm, map_hugetlb, compaction, and
 userfaultfd tests cannot be run due to unmet dependencies.
 
+(cherry picked from commit 946413011af990b7220e73af57c0bc2196275524)
 Bug: 67017050
+Test: make -j vts
+---
+ tools/testing/selftests/vm/run_vmtests.sh | 424 +++++++++++-----------
+ 1 file changed, 212 insertions(+), 212 deletions(-)
 
---- a/tools/testing/selftests/vm/run_vmtests
-+++ b/tools/testing/selftests/vm/run_vmtests
-@@ -8,161 +8,161 @@
+diff --git a/tools/testing/selftests/vm/run_vmtests.sh b/tools/testing/selftests/vm/run_vmtests.sh
+index 71d2dc198fc17..8ea31e76ee9b4 100755
+--- a/tools/testing/selftests/vm/run_vmtests.sh
++++ b/tools/testing/selftests/vm/run_vmtests.sh
+@@ -8,218 +8,218 @@ ksft_skip=4
  mnt=./huge
  exitcode=0
  
@@ -60,7 +72,7 @@ Bug: 67017050
 -fi
 -
 -#filter 64bit architectures
--ARCH64STR="arm64 ia64 mips64 parisc64 ppc64 riscv64 s390x sh64 sparc64 x86_64"
+-ARCH64STR="arm64 ia64 mips64 parisc64 ppc64 ppc64le riscv64 s390x sh64 sparc64 x86_64"
 -if [ -z $ARCH ]; then
 -  ARCH=`uname -m 2>/dev/null | sed -e 's/aarch64.*/arm64/'`
 -fi
@@ -109,14 +121,71 @@ Bug: 67017050
 -	echo "[PASS]"
 -fi
 -
+-echo "-----------------------"
+-echo "running hugepage-mremap"
+-echo "-----------------------"
+-./hugepage-mremap $mnt/huge_mremap
+-if [ $? -ne 0 ]; then
+-	echo "[FAIL]"
+-	exitcode=1
+-else
+-	echo "[PASS]"
+-fi
+-rm -f $mnt/huge_mremap
+-
 -echo "NOTE: The above hugetlb tests provide minimal coverage.  Use"
 -echo "      https://github.com/libhugetlbfs/libhugetlbfs.git for"
 -echo "      hugetlb regression testing."
 -
+-echo "---------------------------"
+-echo "running map_fixed_noreplace"
+-echo "---------------------------"
+-./map_fixed_noreplace
+-if [ $? -ne 0 ]; then
+-	echo "[FAIL]"
+-	exitcode=1
+-else
+-	echo "[PASS]"
+-fi
+-
+-echo "------------------------------------------------------"
+-echo "running: gup_test -u # get_user_pages_fast() benchmark"
+-echo "------------------------------------------------------"
+-./gup_test -u
+-if [ $? -ne 0 ]; then
+-	echo "[FAIL]"
+-	exitcode=1
+-else
+-	echo "[PASS]"
+-fi
+-
+-echo "------------------------------------------------------"
+-echo "running: gup_test -a # pin_user_pages_fast() benchmark"
+-echo "------------------------------------------------------"
+-./gup_test -a
+-if [ $? -ne 0 ]; then
+-	echo "[FAIL]"
+-	exitcode=1
+-else
+-	echo "[PASS]"
+-fi
+-
+-echo "------------------------------------------------------------"
+-echo "# Dump pages 0, 19, and 4096, using pin_user_pages:"
+-echo "running: gup_test -ct -F 0x1 0 19 0x1000 # dump_page() test"
+-echo "------------------------------------------------------------"
+-./gup_test -ct -F 0x1 0 19 0x1000
+-if [ $? -ne 0 ]; then
+-	echo "[FAIL]"
+-	exitcode=1
+-else
+-	echo "[PASS]"
+-fi
+-
 -echo "-------------------"
 -echo "running userfaultfd"
 -echo "-------------------"
--./userfaultfd anon 128 32
+-./userfaultfd anon 20 16
 -if [ $? -ne 0 ]; then
 -	echo "[FAIL]"
 -	exitcode=1
@@ -141,7 +210,7 @@ Bug: 67017050
 -echo "-------------------------"
 -echo "running userfaultfd_shmem"
 -echo "-------------------------"
--./userfaultfd shmem 128 32
+-./userfaultfd shmem 20 16
 -if [ $? -ne 0 ]; then
 -	echo "[FAIL]"
 -	exitcode=1
@@ -215,7 +284,7 @@ Bug: 67017050
 +#fi
 +#
 +##filter 64bit architectures
-+#ARCH64STR="arm64 ia64 mips64 parisc64 ppc64 riscv64 s390x sh64 sparc64 x86_64"
++#ARCH64STR="arm64 ia64 mips64 parisc64 ppc64 ppc64le riscv64 s390x sh64 sparc64 x86_64"
 +#if [ -z $ARCH ]; then
 +#  ARCH=`uname -m 2>/dev/null | sed -e 's/aarch64.*/arm64/'`
 +#fi
@@ -264,14 +333,71 @@ Bug: 67017050
 +#	echo "[PASS]"
 +#fi
 +#
++#echo "-----------------------"
++#echo "running hugepage-mremap"
++#echo "-----------------------"
++#./hugepage-mremap $mnt/huge_mremap
++#if [ $? -ne 0 ]; then
++#	echo "[FAIL]"
++#	exitcode=1
++#else
++#	echo "[PASS]"
++#fi
++#rm -f $mnt/huge_mremap
++#
 +#echo "NOTE: The above hugetlb tests provide minimal coverage.  Use"
 +#echo "      https://github.com/libhugetlbfs/libhugetlbfs.git for"
 +#echo "      hugetlb regression testing."
 +#
++#echo "---------------------------"
++#echo "running map_fixed_noreplace"
++#echo "---------------------------"
++#./map_fixed_noreplace
++#if [ $? -ne 0 ]; then
++#	echo "[FAIL]"
++#	exitcode=1
++#else
++#	echo "[PASS]"
++#fi
++#
++#echo "------------------------------------------------------"
++#echo "running: gup_test -u # get_user_pages_fast() benchmark"
++#echo "------------------------------------------------------"
++#./gup_test -u
++#if [ $? -ne 0 ]; then
++#	echo "[FAIL]"
++#	exitcode=1
++#else
++#	echo "[PASS]"
++#fi
++#
++#echo "------------------------------------------------------"
++#echo "running: gup_test -a # pin_user_pages_fast() benchmark"
++#echo "------------------------------------------------------"
++#./gup_test -a
++#if [ $? -ne 0 ]; then
++#	echo "[FAIL]"
++#	exitcode=1
++#else
++#	echo "[PASS]"
++#fi
++#
++#echo "------------------------------------------------------------"
++#echo "# Dump pages 0, 19, and 4096, using pin_user_pages:"
++#echo "running: gup_test -ct -F 0x1 0 19 0x1000 # dump_page() test"
++#echo "------------------------------------------------------------"
++#./gup_test -ct -F 0x1 0 19 0x1000
++#if [ $? -ne 0 ]; then
++#	echo "[FAIL]"
++#	exitcode=1
++#else
++#	echo "[PASS]"
++#fi
++#
 +#echo "-------------------"
 +#echo "running userfaultfd"
 +#echo "-------------------"
-+#./userfaultfd anon 128 32
++#./userfaultfd anon 20 16
 +#if [ $? -ne 0 ]; then
 +#	echo "[FAIL]"
 +#	exitcode=1
@@ -296,7 +422,7 @@ Bug: 67017050
 +#echo "-------------------------"
 +#echo "running userfaultfd_shmem"
 +#echo "-------------------------"
-+#./userfaultfd shmem 128 32
++#./userfaultfd shmem 20 16
 +#if [ $? -ne 0 ]; then
 +#	echo "[FAIL]"
 +#	exitcode=1
@@ -322,3 +448,6 @@ Bug: 67017050
  
  echo "----------------------"
  echo "running on-fault-limit"
+-- 
+2.36.0.550.gb090851708-goog
+
